fix: fix dvLED crash issue (only black screen)
             Caused by: java.lang.NoSuchMethodError: No virtual method registerActivityLifecycleCallbacks(Landroid/app/Application$ActivityLifecycleCallbacks;)V in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)
             	at androidx.lifecycle.v.a(SourceFile:1)