fix: fix exception issue: The method '*' was called on null
I/flutter ( 8018): 2025-05-09 16:35:14.388735 WARNING onStatsReports NoSuchMethodError: The method '*' was called on null.
I/flutter ( 8018): Receiver: null
I/flutter ( 8018): Tried calling: *(1000)
I/flutter ( 8018): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
I/flutter ( 8018): #1      RtcStatsParser._onVideoStatsReports (package:display_cast_flutter/model/rtc_stats_parser.dart:176:13)
I/flutter ( 8018): #2      RtcStatsParser._onStatsReports (package:display_cast_flutter/model/rtc_stats_parser.dart:79:5)
I/flutter ( 8018): #3      RtcStatsParser.onStatsReports (package:display_cast_flutter/model/rtc_stats_parser.dart:43:7)
I/flutter ( 8018): #4      WebRTCConnector.startStatsTimer.<anonymous closure> (package:display_cast_flutter/model/webrtc_connector.dart:978:28)
I/flutter ( 8018): <asynchronous suspension>