[Fixed] After set TargetAPI to 31, Whiteboard will crash when install on Android 12 device.
FATAL EXCEPTION: MQTT Rec: F4B8DB9680EE1010E854CB4F5339D4E3
    Process: com.viewsonic.droid.loren, PID: 5653
    java.lang.IllegalArgumentException: com.viewsonic.droid.loren: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.